<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3edi\models\base;

use Yii;


/**
 * This is the base-model class for table "edi_message_ref".
 *
 * @property integer $id
 * @property integer $message_id
 * @property integer $sys_model_id
 * @property integer $ref_record_id
 *
 * @property \d3yii2\d3edi\models\EdiMessage $message
 * @property \d3yii2\d3edi\models\SysModels $sysModel
 * @property string $aliasModel
 */
abstract class EdiMessageRef extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'edi_message_ref';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = [
        ];
        return $behaviors;
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'tinyint Unsigned' => [['sys_model_id'],'integer' ,'min' => 0 ,'max' => 255],
            'integer Unsigned' => [['id','message_id','ref_record_id'],'integer' ,'min' => 0 ,'max' => 4294967295],
            [['message_id', 'sys_model_id', 'ref_record_id'], 'required'],
            [['sys_model_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3edi\models\SysModels::className(), 'targetAttribute' => ['sys_model_id' => 'id']],
            [['message_id'], 'exist', 'skipOnError' => true, 'targetClass' => \d3yii2\d3edi\models\EdiMessage::className(), 'targetAttribute' => ['message_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'message_id' => 'Message ID',
            'sys_model_id' => 'Sys Model ID',
            'ref_record_id' => 'Ref Record ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMessage()
    {
        return $this->hasOne(\d3yii2\d3edi\models\EdiMessage::className(), ['id' => 'message_id'])->inverseOf('ediMessageRefs');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSysModel()
    {
        return $this->hasOne(\d3yii2\d3edi\models\SysModels::className(), ['id' => 'sys_model_id'])->inverseOf('ediMessageRefs');
    }


    
    /**
     * @inheritdoc
     * @return \d3yii2\d3edi\models\EdiMessageRefQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \d3yii2\d3edi\models\EdiMessageRefQuery(get_called_class());
    }


}
