<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace d3yii2\d3edi\models\base;

use Yii;


/**
 * This is the base-model class for table "edi_message_type".
 *
 * @property integer $id
 * @property string $code
 *
 * @property \d3yii2\d3edi\models\EdiMessage[] $ediMessages
 * @property string $aliasModel
 */
abstract class EdiMessageType extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return 'edi_message_type';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            'tinyint Unsigned' => [['id'],'integer' ,'min' => 0 ,'max' => 255],
            [['code'], 'required'],
            [['code'], 'string', 'max' => 6]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'code' => 'Code',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEdiMessages()
    {
        return $this->hasMany(\d3yii2\d3edi\models\EdiMessage::className(), ['message_type_id' => 'id'])->inverseOf('messageType');
    }


    
    /**
     * @inheritdoc
     * @return \d3yii2\d3edi\models\EdiMessageTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \d3yii2\d3edi\models\EdiMessageTypeQuery(get_called_class());
    }


}
